name: Deploy Vite Client to GitHub Pages

on:
    push:
        branches:
            - "client/**"
            - ".github/workflows/deploy-client.yml"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./client

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./client/dist
